CREATE DATABASE IF NOT EXISTS OpenMVdb DEFAULT CHARACTER SET utf8mb4;

USE OpenMVdb;

CREATE TABLE IF NOT EXISTS face_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    feature_vector BLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
